version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=jdbc:postgresql://auth-springtodo-1:5432/springtodo
    ports:
      - 8090:8090
    depends_on:
      - springtodo
  springtodo:
    image: postgres:15.3
    ports:
      - 5457:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=springtodo
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    command: postgres -c max_connections=50 -c log_min_messages=LOG