version: '3'

services:
  springtodo:
    image: postgres:13.1
    container_name: 'authsys'
    ports:
      - 5457:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=springtodo
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    command: postgres -c max_connections=50 -c log_min_messages=LOG