#SECRET_KEY: h47Iy/IJzMcI3gTXXaKZLVKcoypkSaHd52la8XhgZV0sVTaqc6z797MkdnlK/SyD
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8090
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/springtodo}
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    username: ${MAIL_USERNAME:balgaliev.azat.03@gmail.com}
    password: ${MAIL_PASS:nldpfmniiwuhuked}
    port: ${MAIL_PORT:587}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
        debug: true
    protocol: smtp
logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
    org.springframework: INFO
    com.todo.auth: DEBUG
