server:
  port: 8080
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/springtodo}
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: balgaliev.azat.03@gmail.com
    password: nldpfmniiwuhuked
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
logging:
  level:
    org:
      springframework:
        security=DEBUG:
